### ISSUE TITLE
timed out isotp_socket.recv()

### ISSUE THREAD

**Issue by pompushko** [pylessard/python-can-isotp#117]
Hello

I upgraded isotp up to the last version and my old app stop works :D

```
import isotp
from uds import routines
from loggers.logger_app import logger

def start(CAN_INTERFACE, ECU_NAME, UDS_ECU_ADDRESS, UDS_TARGET_ADDRESS):
    isotp_socket = create_isotp_socket(CAN_INTERFACE, UDS_ECU_ADDRESS, UDS_TARGET_ADDRESS)
    while True:
        request = isotp_socket.recv()
        if request is not None:
            log_request(ECU_NAME, UDS_ECU_ADDRESS, UDS_TARGET_ADDRESS, request)
            if len(request) >= 1:
                response = routines.process_service_request(ECU_NAME, request)
                if response is not None:
                    log_response(UDS_ECU_ADDRESS, response)
                    isotp_socket.send(response)

def create_isotp_socket(CAN_INTERFACE, receiver_address, target_address):
    socket = isotp.socket(timeout=1)
    socket.bind(CAN_INTERFACE, isotp.Address(isotp.AddressingMode.Normal_29bits, rxid=receiver_address, txid=target_address))
    return socket
```

Here is main code which is run my thread:
```
Thread(target=uds_listener.start, args = (ecu_interface, ecu, ecu_request_address, ecu_response_address)).start()
```

```
Exception in thread Thread-1 (start):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
Exception in thread Thread-2 (start):
Traceback (most recent call last):
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
  File "/home/pi/ecu-simulator/uds/listener.py", line 8, in start
    request = isotp_socket.recv()
              ^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/isotp/tpsock/__init__.py", line 113, in recv
    return self._socket.recv(bufsize, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: timed out
```

Maybe I have some problems with my thread creation? Thank you

**Comment by pylessard** [comment]
No, check the release note. Recv throws timeout instead of returning None with v2.x

**Comment by pylessard** [comment]
![Screenshot_20240209-130919](https://github.com/pylessard/python-can-isotp/assets/2386969/94807ed6-b8ec-43de-a1af-bcc3017fb9e0)

**Comment by pompushko** [comment]
Great, could you please help me, what to change, to get it works :D?
Unfortunately, I`m not well in Python yet...

**Comment by pylessard** [comment]
Comes from #46

**Comment by pylessard** [comment]
```
try:
...
except socket.TimeoutError: 
    pass
```

**Comment by pompushko** [comment]
> ```
> try:
> ...
> except socket.TimeoutError: 
>     pass
> ```


Unfortunately, cant get it works:
```
    except isotp.TimeoutError:
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'socket' object has no attribute 'TimeoutError'
```

**Comment by pylessard** [comment]
``TimeoutError`` is defined in the python ``socket`` module.

```
import socket

try:
    ...
except socket.TimeoutError:
    pass
```
